language: python
python:
  - 3.6

before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a

install:
  - conda install numpy
  - conda install scipy
  - conda install matplotlib
  - conda install pandas
  - conda install cvxpy
  - conda install -y -c cvxgrp cvxpy
  - conda install -y -c anaconda cvxopt
  - conda update numpy

script:
  - python --version
  - ./runtests.sh
