name: circleci-artifacts-redirector-action
on: [status]
jobs:
  circleci_artifacts_redirector_job:
    runs-on: ubuntu-latest
    name: Run CircleCI artifacts redirector!!
    steps:
      - name: run-circleci-artifacts-redirector
        uses: larsoner/circleci-artifacts-redirector-action@0.3.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-path: 0/html/index.html
          circleci-jobs: build_doc
